[[redirects]]
  from = "/*"
  to = "https://exercises.vercel.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/grid"
  to = "https://exercises.vercel.app/grid"
  status = 301

[[redirects]]
  from = "/subgrid"
  to = "https://exercises.vercel.app/subgrid"
  status = 301

[[redirects]]
  from = "/flex"
  to = "https://exercises.vercel.app/flex"
  status = 301

[[redirects]]
  from = "/defensive"
  to = "https://exercises.vercel.app/defensive"
  status = 301